version: '3'

services:
  redis-server:
    image: redis
  agency-backend:
    restart: unless-stopped
    build: 
      context: backend
      dockerfile: Dockerfile
    environment:
      MONGO_DRIVER: "mongodb+srv://todo-app:UfzyNzvsWU2cV2XF@cluster0.51m09.mongodb.net/outcast-inc?retryWrites=true&w=majority&appName=Cluster0"
    ports:
      - "9000:9000"
      - "4000:4000"
  agency-frontend:
    restart: unless-stopped
    build: 
      context: refine-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - agency-backend